version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rmq_main
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - rmq_network
networks:
  rmq_network:
    external: true