"""Add column likes to product

Revision ID: 0df0f365d1a9
Revises: 1613e5f97dbc
Create Date: 2025-03-13 09:20:08.501734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0df0f365d1a9'
down_revision = '1613e5f97dbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('like')

    # ### end Alembic commands ###
