"""Rename column like to likes

Revision ID: f7713e603fdd
Revises: 0df0f365d1a9
Create Date: 2025-03-13 09:21:16.994216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7713e603fdd'
down_revision = '0df0f365d1a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))
        batch_op.drop_column('like')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('likes')

    # ### end Alembic commands ###
